development:
  adapter: postgresql
  database: montreal_rb_tools_development

test:
  adapter: postgresql
  database: montreal_rb_tools_test

production:
  adapter: postgresql
  database: montreal_rb_tools_production
